server:
  port: 8884
spring:
  kafka:
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: microkafka-order-query-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: order:microkafka.escqrs.orders.query.model.OrderCreatedEvent
  datasource:
    url: jdbc:h2:mem:ms-escqrs-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  h2:
    console:
      enabled: true
